### ISSUE TITLE
function is not covered

### ISSUE THREAD

**Issue by mustafaozhan** [mockative/mockative#25] opened 2022-02-23 21:16 UTC
Hello 👋 

when I convert 
```kotlin
            given(sessionManager)
                .invocation { sessionManager.checkAppUpdate(false) }
                .then { null }

            given(sessionManager)
                .invocation { sessionManager.checkAppUpdate(true) }
                .then { null }
```
into this
```kotlin
            given(sessionManager)
                .function(sessionManager::checkAppUpdate) // the line is not covered
                .whenInvokedWith(any())
                .thenReturn(null)
```
the line with `function` is not covered. As you can imagine it decreases the overall coverage :) Would it be possible to cover `function` ?

**Comment by Nillerr** [comment] 2022-05-14 08:59
Hi @mustafaozhan

First of all, I'd like to apologize for my absence.

I don't believe there's a way for me to solve this specific issue since Mockative doesn't affect code coverage itself. I suggest you reach out to the team behind the coverage tool you're using.

**Comment by mustafaozhan** [comment] 2022-05-14 09:26
Hey @Nillerr no worries, now looking it again maybe it can ben related with this issue that I have created for `kover` https://github.com/Kotlin/kotlinx-kover/issues/154

**Comment by Nillerr** [comment] 2022-06-28 07:13
I'm closing this issue since I'm quite certain the issue is not with Mockative.

**Closed by Nillerr** 2022-06-28 07:13 UTC
